/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.View;

import br.com.DAO.AlunosDAO;
import br.com.Factory.ConnectionFactory;
import br.com.Model.ModelAlunos;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Rafael Medeiros
 */
public class Declaracoes extends javax.swing.JFrame {

    private Connection connection;

    public void pesquisaAlunos_porNome() {

        DefaultTableModel tabelaAlunos = (DefaultTableModel) jTablePesquisa.getModel();
        AlunosDAO adao = new AlunosDAO();
        try {
            tabelaAlunos.setNumRows(0);
            for (ModelAlunos mA : adao.pesquisarAlunos(jTextFieldNome.getText())) {
                tabelaAlunos.addRow(new Object[]{
                    mA.getRA(),
                    mA.getNome()
                });
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    public Declaracoes() {
        initComponents();
        setIconImage(new ImageIcon("Img/iconeSistema.png").getImage());
        setTitle("GSA - Gerenciamento de Secretaria Agil  ");
        pesquisaAlunos_porNome();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextFieldRA = new javax.swing.JTextField();
        jTextFieldPeriodo = new javax.swing.JTextField();
        jTextFieldDataNasc = new javax.swing.JTextField();
        Fundo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldNome = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNomeSelected = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jRadioButtonEscolaridade = new javax.swing.JRadioButton();
        jRadioButtonTransferencia = new javax.swing.JRadioButton();
        jRadioButtonConclusao = new javax.swing.JRadioButton();
        jRadioButtonVaga = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonAssinatura = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jTextFieldRA.setEditable(false);

        jTextFieldPeriodo.setEditable(false);

        jTextFieldDataNasc.setEditable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Pesquise o aluno que deseja emitir a declaração e clique no mesmo.");

        jTextFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNomeKeyReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RA", "NOME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePesquisa.getTableHeader().setReorderingAllowed(false);
        jTablePesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePesquisa);
        if (jTablePesquisa.getColumnModel().getColumnCount() > 0) {
            jTablePesquisa.getColumnModel().getColumn(0).setResizable(false);
            jTablePesquisa.getColumnModel().getColumn(0).setPreferredWidth(130);
            jTablePesquisa.getColumnModel().getColumn(1).setResizable(false);
            jTablePesquisa.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Você selecionou:");

        jTextFieldNomeSelected.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Escolha qual declaração emitir:");

        buttonGroup1.add(jRadioButtonEscolaridade);
        jRadioButtonEscolaridade.setText("Escolaridade");

        buttonGroup1.add(jRadioButtonTransferencia);
        jRadioButtonTransferencia.setText("Transferência");

        buttonGroup1.add(jRadioButtonConclusao);
        jRadioButtonConclusao.setText("Conclusão");

        buttonGroup1.add(jRadioButtonVaga);
        jRadioButtonVaga.setText("Vaga Concedida");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Emitir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Img/icons8-documentos-40.png"))); // NOI18N

        jRadioButtonAssinatura.setText("Assinada Digitalmente");

        javax.swing.GroupLayout FundoLayout = new javax.swing.GroupLayout(Fundo);
        Fundo.setLayout(FundoLayout);
        FundoLayout.setHorizontalGroup(
            FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FundoLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(FundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FundoLayout.createSequentialGroup()
                        .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FundoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                                .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FundoLayout.createSequentialGroup()
                                        .addComponent(jRadioButtonConclusao)
                                        .addGap(12, 12, 12)
                                        .addComponent(jRadioButtonVaga))
                                    .addGroup(FundoLayout.createSequentialGroup()
                                        .addComponent(jRadioButtonEscolaridade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonTransferencia)))
                                .addGap(122, 122, 122))
                            .addGroup(FundoLayout.createSequentialGroup()
                                .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jButton1)
                                    .addGroup(FundoLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldNomeSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(FundoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonAssinatura)
                        .addGap(23, 23, 23))))
        );
        FundoLayout.setVerticalGroup(
            FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButtonAssinatura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonEscolaridade)
                    .addComponent(jRadioButtonTransferencia))
                .addGap(7, 7, 7)
                .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonConclusao)
                    .addComponent(jRadioButtonVaga))
                .addGap(13, 13, 13)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jMenu1.setText("Atalhos");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem1.setText("Atualizar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(484, 627));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeKeyReleased
        pesquisaAlunos_porNome();
    }//GEN-LAST:event_jTextFieldNomeKeyReleased
    public void buscaInformacoes() {
        ModelAlunos mA = new ModelAlunos();
        mA.setRA(jTextFieldRA.getText());
        AlunosDAO adao = new AlunosDAO();
        adao.pesquisaCampos(mA);
        jTextFieldPeriodo.setText(mA.getPeriodo());
        jTextFieldDataNasc.setText(mA.getDataNasc());
    }
    private void jTablePesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisaMouseClicked
        int setar = jTablePesquisa.getSelectedRow();
        jTextFieldRA.setText(jTablePesquisa.getModel().getValueAt(setar, 0).toString());
        jTextFieldNomeSelected.setText(jTablePesquisa.getModel().getValueAt(setar, 1).toString());
        buscaInformacoes();
    }//GEN-LAST:event_jTablePesquisaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTextFieldNomeSelected.getText().isEmpty()) {
            if (jRadioButtonVaga.isSelected()) {
                
                String nome = JOptionPane.showInputDialog("Informe o nome do aluno que solicitou a vaga");
                String serieS = JOptionPane.showInputDialog("Informe qual o ano solicitado para matricula.");
                String prazo = JOptionPane.showInputDialog("Informe qual o prazo máximo para a entrega dos documentos.");
                if (serieS != "" && prazo != "") {
                    if (jRadioButtonAssinatura.isSelected()) {
                        
                         try {
                        this.connection = new ConnectionFactory().getConnection();
                        HashMap param = new HashMap();
                        param.put("nome", nome);
                        param.put("serieS", serieS);
                        param.put("prazo", prazo);
                        
                        JasperPrint rel = null;
                        rel = JasperFillManager.fillReport("Util/modelDeclaracao_Vaga_Assinado.jasper", param, connection);
                        JasperViewer.viewReport(rel, false);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                    }
                    
                    } else {
                    try {
                        this.connection = new ConnectionFactory().getConnection();
                        HashMap param = new HashMap();
                        param.put("nome", nome);
                        param.put("serieS", serieS);
                        param.put("prazo", prazo);
                        
                        JasperPrint rel = null;
                        rel = JasperFillManager.fillReport("Util/modelDeclaracao_Vaga.jasper", param, connection);
                        JasperViewer.viewReport(rel, false);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                    }
                }
                }

            } else {
                JOptionPane.showMessageDialog(null, "Selecione o aluno qual deseja emitir uma declaração!", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            if (jRadioButtonEscolaridade.isSelected()) {
                String ano = JOptionPane.showInputDialog(null, "Informe o ano na qual se encontra o aluno ( Exemplo: 2º )");
                String abc = JOptionPane.showInputDialog(null, "Informe se o aluno se encontra na classe (A, B ou C)");

                if (ano != "") {
                    
                    if (jRadioButtonAssinatura.isSelected()) {
                    
                     try {
                        this.connection = new ConnectionFactory().getConnection();
                        HashMap param = new HashMap();
                        param.put("ano", ano);
                        param.put("nome", jTextFieldNomeSelected.getText());
                        param.put("ra", jTextFieldRA.getText());
                        param.put("abc", abc);
                        JasperPrint rel = null;
                        rel = JasperFillManager.fillReport("Util/modelDeclaracao_Escolaridade_Assinado.jasper", param, connection);
                        JasperViewer.viewReport(rel, false);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                    }
                    
                    
                    }
                    
                    else {
                    try {
                        this.connection = new ConnectionFactory().getConnection();
                        HashMap param = new HashMap();
                        param.put("ano", ano);
                        param.put("nome", jTextFieldNomeSelected.getText());
                        param.put("ra", jTextFieldRA.getText());
                        param.put("abc", abc);
                        JasperPrint rel = null;
                        rel = JasperFillManager.fillReport("Util/modelDeclaracao_Escolaridade.jasper", param, connection);
                        JasperViewer.viewReport(rel, false);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                    }
                }
                }

            } else {
                if (jRadioButtonConclusao.isSelected()) {
                    String serie = JOptionPane.showInputDialog("Informe a série/ano concluido. (Exemplo: 5)");
                    String anoC = JOptionPane.showInputDialog("Informe o ano em que foi concluido. (Exemplo: 2019)");
                    if (serie != "" && anoC != "") {
                        
                        if (jRadioButtonAssinatura.isSelected()) {
                        
                          try {
                            this.connection = new ConnectionFactory().getConnection();
                            HashMap param = new HashMap();
                            param.put("ano", anoC);
                            param.put("serie", serie);
                            param.put("nome", jTextFieldNomeSelected.getText());
                            param.put("ra", jTextFieldRA.getText());
                            JasperPrint rel = null;
                            rel = JasperFillManager.fillReport("Util/modelDeclaracao_Conclusao_Assinado.jasper", param, connection);
                            JasperViewer.viewReport(rel, false);
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex.getMessage());
                        }
                    } else {
                        
                        
                        try {
                            this.connection = new ConnectionFactory().getConnection();
                            HashMap param = new HashMap();
                            param.put("ano", anoC);
                            param.put("serie", serie);
                            param.put("nome", jTextFieldNomeSelected.getText());
                            param.put("ra", jTextFieldRA.getText());
                            JasperPrint rel = null;
                            rel = JasperFillManager.fillReport("Util/modelDeclaracao_Conclusao.jasper", param, connection);
                            JasperViewer.viewReport(rel, false);
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex.getMessage());
                        }
                    }
                    }

                } else {
                    if (jRadioButtonTransferencia.isSelected()) {
                        String prazo = JOptionPane.showInputDialog("Informe o prazo para a emissão dos documentos do aluno.");
                        String serie = JOptionPane.showInputDialog("Informe qual ano/série o aluno está apto para se matricular.");
                        if (serie != "" && prazo != "") {
                            
                            if (jRadioButtonAssinatura.isSelected()) {
                            
                             try {
                                this.connection = new ConnectionFactory().getConnection();
                                HashMap param = new HashMap();
                                param.put("prazo", prazo);
                                param.put("serie", serie);
                                param.put("nome", jTextFieldNomeSelected.getText());
                                param.put("ra", jTextFieldRA.getText());
                                JasperPrint rel = null;
                                rel = JasperFillManager.fillReport("Util/modelDeclaracao_Transferencia_Assinado.jasper", param, connection);
                                JasperViewer.viewReport(rel, false);
                            } catch (Exception ex) {
                                JOptionPane.showMessageDialog(null, ex.getMessage());
                            }
                            
                            } else {

                            try {
                                this.connection = new ConnectionFactory().getConnection();
                                HashMap param = new HashMap();
                                param.put("prazo", prazo);
                                param.put("serie", serie);
                                param.put("nome", jTextFieldNomeSelected.getText());
                                param.put("ra", jTextFieldRA.getText());
                                JasperPrint rel = null;
                                rel = JasperFillManager.fillReport("Util/modelDeclaracao_Transferencia.jasper", param, connection);
                                JasperViewer.viewReport(rel, false);
                            } catch (Exception ex) {
                                JOptionPane.showMessageDialog(null, ex.getMessage());
                            }
                        }
                        }

                    } else {

                    }
                }

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        new Declaracoes().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Declaracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Declaracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Declaracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Declaracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Declaracoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fundo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonAssinatura;
    private javax.swing.JRadioButton jRadioButtonConclusao;
    private javax.swing.JRadioButton jRadioButtonEscolaridade;
    private javax.swing.JRadioButton jRadioButtonTransferencia;
    private javax.swing.JRadioButton jRadioButtonVaga;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTablePesquisa;
    public javax.swing.JTextField jTextFieldDataNasc;
    private javax.swing.JTextField jTextFieldNome;
    public javax.swing.JTextField jTextFieldNomeSelected;
    public javax.swing.JTextField jTextFieldPeriodo;
    public javax.swing.JTextField jTextFieldRA;
    // End of variables declaration//GEN-END:variables
}
