/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.View;

import br.com.DAO.HistoricoDAO;
import br.com.Model.ModelHistorico;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael Medeiros
 */
public class HistoricoP1 extends javax.swing.JDialog {

    HistoricoDAO hdao = new HistoricoDAO();
    ModelHistorico mH = new ModelHistorico();

    public HistoricoP1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldRM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldRA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCidadeNasc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldDataNasc = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxEstados = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNacionalidade = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("RM:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("RA:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Nascimento:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Data Nascimento:");

        try {
            jFormattedTextFieldDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Cabeçalho");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Estado:");

        jComboBoxEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Nacionalidade:");

        jButton1.setText("Avançar >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jFormattedTextFieldDataNasc))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldRA, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel4)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldCidadeNasc)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxEstados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldRM, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator3))
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldRM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldRA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldCidadeNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jFormattedTextFieldDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBoxEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(488, 315));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        public void pesquisaNotas() {
        
        mH.setRm(Integer.parseInt(jTextFieldRM.getText()));
        hdao.pesquisaNotas(mH);
        historicoPART2 hp = new historicoPART2();
        hp.jTextField1AnoLP.setText(mH.getPrimeiroAnoLP());
        hp.jTextField1AnoArte.setText(mH.getPrimerioAnoArte());
        hp.jTextField1AnoEdFisica.setText(mH.getPrimeiroAnoEDFisica());
        hp.jTextField1AnoHist.setText(mH.getPrimerioAnoHistoria());
        hp.jTextField1AnoGeo.setText(mH.getPrimeiroAnoGeo());
        hp.jTextField1AnoMat.setText(mH.getPrimeiroAnoMat());
        hp.jTextField1AnoCienc.setText(mH.getPrimeiroAnoCienc());
        hp.jTextField1AnoIngl.setText(mH.getPrimeiroAnoIngl());
        
        
        
        
        }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTextFieldNome.getText().isEmpty()
                || jTextFieldRM.getText().isEmpty()
                || jTextFieldRA.getText().isEmpty()
                || jTextFieldCidadeNasc.getText().isEmpty()
                || jFormattedTextFieldDataNasc.getText().isEmpty()
                || jTextFieldNacionalidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para poder avançar!", "Alerta", JOptionPane.WARNING_MESSAGE);

        } else {

            mH.setNome(jTextFieldNome.getText());
            mH.setRm(Integer.parseInt(jTextFieldRM.getText()));
            mH.setRa(jTextFieldRA.getText());
            mH.setNascimento(jTextFieldCidadeNasc.getText());
            mH.setNacionalidade(jTextFieldNacionalidade.getText());
            mH.setEstado(String.valueOf(jComboBoxEstados.getSelectedItem()));
            mH.setDataNasc(jFormattedTextFieldDataNasc.getText());
            hdao.verificaRegistro(mH);
            
            if (mH.isExistente() == true) {
                pesquisaNotas();
                hdao.atualizaDados(mH);
                hdao.atualizaDados_Aluno(mH);
                JOptionPane.showMessageDialog(null, "Como foi identificado um histórico cadastrado apenas atualizamos os dados!");
                this.dispose();
                historicoPART2 hp2 = new historicoPART2();
                hp2.rm = Integer.parseInt(jTextFieldRM.getText());
                hdao.pesquisaNotas(mH);
                hp2.jTextField1AnoLP.setText(mH.getPrimeiroAnoLP());
                hp2.jTextField1AnoArte.setText(mH.getPrimerioAnoArte());
                hp2.jTextField1AnoEdFisica.setText(mH.getPrimeiroAnoEDFisica());
                hp2.jTextField1AnoHist.setText(mH.getPrimerioAnoHistoria());
                hp2.jTextField1AnoGeo.setText(mH.getPrimeiroAnoGeo());
                hp2.jTextField1AnoMat.setText(mH.getPrimeiroAnoMat());
                hp2.jTextField1AnoCienc.setText(mH.getPrimeiroAnoCienc());
                hp2.jTextField1AnoIngl.setText(mH.getPrimeiroAnoIngl());
                
                hp2.jTextField2AnoLP.setText(mH.getSegundoAnoLP());
                hp2.jTextField2AnoArte.setText(mH.getSegundoAnoArte());
                hp2.jTextField2AnoEdFisica.setText(mH.getSegundoAnoEDFisica());
                hp2.jTextField2AnoHist.setText(mH.getSegundoAnoHistoria());
                hp2.jTextField2AnoGeo.setText(mH.getSegundoAnoGeo());
                hp2.jTextField2AnoMat.setText(mH.getSegundoAnoMat());
                hp2.jTextField2AnoCienc.setText(mH.getSegundoAnoCienc());
                hp2.jTextField2AnoIngl.setText(mH.getSegundoAnoIngl());
                
                hp2.jTextField3AnoLP.setText(mH.getTerceiroAnoLP());
                hp2.jTextField3AnoArte.setText(mH.getTerceiroAnoArte());
                hp2.jTextField3AnoEdFisica.setText(mH.getTerceiroAnoEDFisica());
                hp2.jTextField3AnoHist.setText(mH.getTerceiroAnoHistoria());
                hp2.jTextField3AnoGeo.setText(mH.getTerceiroAnoGeo());
                hp2.jTextField3AnoMat.setText(mH.getTerceiroAnoMat());
                hp2.jTextField3AnoCienc.setText(mH.getTerceiroAnoCienc());
                hp2.jTextField3AnoIngl.setText(mH.getTerceiroAnoIngl());
                
                hp2.jTextField4AnoLP.setText(mH.getQuartoAnoLP());
                hp2.jTextField4AnoArte.setText(mH.getQuartoAnoArte());
                hp2.jTextField4AnoEdFisica.setText(mH.getQuartoAnoEDFisica());
                hp2.jTextField4AnoHist.setText(mH.getQuartoAnoHistoria());
                hp2.jTextField4AnoGeo.setText(mH.getQuartoAnoGeo());
                hp2.jTextField4AnoMat.setText(mH.getQuartoAnoMat());
                hp2.jTextField4AnoCienc.setText(mH.getQuartoAnoCienc());
                hp2.jTextField4AnoIngl.setText(mH.getQuartoAnoIngl());
                
                hp2.jTextField5AnoLP.setText(mH.getQuintoAnoLP());
                hp2.jTextField5AnoArte.setText(mH.getQuintoAnoArte());
                hp2.jTextField5AnoEdFisica.setText(mH.getQuintoAnoEDFisica());
                hp2.jTextField5AnoHist.setText(mH.getQuintoAnoHistoria());
                hp2.jTextField5AnoGeo.setText(mH.getQuintoAnoGeo());
                hp2.jTextField5AnoMat.setText(mH.getQuintoAnoMat());
                hp2.jTextField5AnoCienc.setText(mH.getQuintoAnoCienc());
                hp2.jTextField5AnoIngl.setText(mH.getQuintoAnoIngl());
                
                hp2.show();
                
            }
            else {
            hdao.gravaCabecalho(mH);
            hdao.atualizaDados_Aluno(mH);
            JOptionPane.showMessageDialog(null, "Cabeçalho preenchido com sucesso!");
            this.dispose();
            historicoPART2 hp2 = new historicoPART2();
            hp2.rm = mH.getRm();
            
            hp2.show();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoricoP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoricoP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoricoP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoricoP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HistoricoP1 dialog = new HistoricoP1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JComboBox<String> jComboBoxEstados;
    public javax.swing.JFormattedTextField jFormattedTextFieldDataNasc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JTextField jTextFieldCidadeNasc;
    public javax.swing.JTextField jTextFieldNacionalidade;
    public javax.swing.JTextField jTextFieldNome;
    public javax.swing.JTextField jTextFieldRA;
    public javax.swing.JTextField jTextFieldRM;
    // End of variables declaration//GEN-END:variables
}
